#!/bin/bash
### BEGIN INIT INFO
# Provides:          github-runner
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GitHub Actions Runner
# Description:       Self-hosted GitHub Actions Runner
### END INIT INFO

NAME="github-runner-mos_releases"
USER="root"
DAEMON="github-runner-mos_releases"
ROOT_DIR=/root/runner/mos-releases
PIDFILE="/var/run/runner-mos_releases.pid"
DAEMON="$ROOT_DIR/run.sh"

export RUNNER_ALLOW_RUNASROOT="1"

start() {
    echo -n "Starting $NAME: "
    start-stop-daemon --start \
        --quiet \
        --pidfile $PIDFILE \
        --make-pidfile \
        --background \
        --chuid $USER \
        --chdir $ROOT_DIR \
        --exec $DAEMON
    
    if [ $? -eq 0 ]; then
        echo "OK"
        return 0
    else
        echo "FAILED"
        return 1
    fi
}

stop() {
    echo -n "Stopping $NAME: "
    if [ -f "$PIDFILE" ]; then
        PID=$(cat "$PIDFILE")
        PGID=$(ps -o pgid= -p "$PID" 2>/dev/null | tr -d ' ')
        if [ -n "$PGID" ]; then
            kill -SIGTERM -"$PGID" 2>/dev/null
        fi
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "No PID file found"
    fi
}

status() {
    start-stop-daemon --status --pidfile $PIDFILE --user $USER
    case $? in
        0)
            echo "$NAME is running with PID $(cat $PIDFILE)"
            return 0
            ;;
        1)
            echo "$NAME is not running (but pidfile exists)"
            return 1
            ;;
        3)
            echo "$NAME is not running"
            return 1
            ;;
        *)
            echo "$NAME status unknown"
            return 1
            ;;
    esac
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $?
